-- MySQL Script generated by MySQL Workbench
-- qua 09 out 2024 20:34:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema AgroFlorestaSIM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AgroFlorestaSIM` ;

-- -----------------------------------------------------
-- Schema AgroFlorestaSIM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AgroFlorestaSIM` DEFAULT CHARACTER SET utf8mb4 ;
USE `AgroFlorestaSIM` ;

-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Coleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Coleta` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Coleta` (
  `idColeta` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Coleta` ENUM('1', '2', '3') NULL COMMENT 'Capinas manuais, mecânicas ou químicas, dependendo da área',
  `Sistema_idSistema` INT(11) NULL,
  PRIMARY KEY (`idColeta`),
  INDEX `fk_Coleta_Sistema1_idx` (`Sistema_idSistema` ASC) VISIBLE,
  CONSTRAINT `fk_Coleta_Sistema1`
    FOREIGN KEY (`Sistema_idSistema`)
    REFERENCES `AgroFlorestaSIM`.`Sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Culturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Culturas` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Culturas` (
  `idCulturas` INT(11) NOT NULL AUTO_INCREMENT,
  `NomeCultura` VARCHAR(100) NULL COMMENT 'Tipos de cultura',
  `Tipo_Cultivo` ENUM('1', '2', '3', '4', '5', '6', '9') NULL DEFAULT NULL COMMENT 'tipos de cultivo com base em diferentes critérios, como ciclo de vida da planta, método de cultivo ou práticas agrícolas específicas.\\\\\\\\n1- Perene;\\\\\\\\n2- Anual;\\\\\\\\n3- Bienal;\\\\\\\\n4-Hidropônico;\\\\\\\\n5-Orgânico;\\\\\\\\n6-Convêncional;',
  `Atrai` VARCHAR(500) NULL DEFAULT NULL COMMENT 'Que tipos de animais ou insetos são atraídos pela cultura em questão:',
  `PropositoCultivo` INT(11) NULL,
  `Tamanho` ENUM('1', '2', '3', '4', '5') NULL COMMENT '1- Grande porte\n2- Médio porte\n3- Pequeno porte\n4-Leiras\n5-rasteiras\n',
  `Ciclo` INT NULL COMMENT 'Ciclo de colheita em dias',
  `PropositoCultivo_idPropositoCultivo` INT NULL,
  `TipoCultivo_idTipoCultivo` INT NULL,
  `Cultura_Tratamento_idCultura_Tratamento` INT NULL,
  PRIMARY KEY (`idCulturas`),
  INDEX `fk_Culturas_TipoCultivo1_idx` (`PropositoCultivo` ASC) VISIBLE,
  INDEX `fk_Culturas_PropositoCultivo1_idx` (`PropositoCultivo_idPropositoCultivo` ASC) VISIBLE,
  INDEX `fk_Culturas_TipoCultivo2_idx` (`TipoCultivo_idTipoCultivo` ASC) VISIBLE,
  INDEX `fk_Culturas_Cultura_Tratamento1_idx` (`Cultura_Tratamento_idCultura_Tratamento` ASC) VISIBLE,
  CONSTRAINT `fk_Culturas_TipoCultivo1`
    FOREIGN KEY (`PropositoCultivo`)
    REFERENCES `AgroFlorestaSIM`.`Culturas_caracteristicas` (`idCaracteristicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Culturas_PropositoCultivo1`
    FOREIGN KEY (`PropositoCultivo_idPropositoCultivo`)
    REFERENCES `AgroFlorestaSIM`.`PropositoCultivo` (`idPropositoCultivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Culturas_TipoCultivo2`
    FOREIGN KEY (`TipoCultivo_idTipoCultivo`)
    REFERENCES `AgroFlorestaSIM`.`TipoCultivo` (`idTipoCultivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Culturas_Cultura_Tratamento1`
    FOREIGN KEY (`Cultura_Tratamento_idCultura_Tratamento`)
    REFERENCES `AgroFlorestaSIM`.`Cultura_Tratamento` (`idCultura_Tratamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Culturas_caracteristicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Culturas_caracteristicas` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Culturas_caracteristicas` (
  `idCaracteristicas` INT(11) NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NULL,
  `Custo_Semente` FLOAT NULL,
  `Pragas` MEDIUMTEXT NULL,
  `Doencas` MEDIUMTEXT NULL,
  `AnomaliaFisiologica` MEDIUMTEXT NULL,
  PRIMARY KEY (`idCaracteristicas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Culturas_has_Requisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Culturas_has_Requisitos` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Culturas_has_Requisitos` (
  `Culturas_idCulturas` INT(11) NOT NULL,
  `Requisitos_idRequisitos` INT(11) NOT NULL,
  INDEX `fk_Culturas_has_Requisitos_Requisitos1_idx` (`Requisitos_idRequisitos` ASC) VISIBLE,
  INDEX `fk_Culturas_has_Requisitos_Culturas1_idx` (`Culturas_idCulturas` ASC) VISIBLE,
  CONSTRAINT `fk_Culturas_has_Requisitos_Culturas1`
    FOREIGN KEY (`Culturas_idCulturas`)
    REFERENCES `AgroFlorestaSIM`.`Culturas` (`idCulturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Culturas_has_Requisitos_Requisitos1`
    FOREIGN KEY (`Requisitos_idRequisitos`)
    REFERENCES `AgroFlorestaSIM`.`Requisitos` (`idRequisitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Cultura_Tratamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Cultura_Tratamento` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Cultura_Tratamento` (
  `idCultura_Tratamento` INT NOT NULL AUTO_INCREMENT,
  `SoloPreparado` MEDIUMTEXT NULL,
  `Tiposolo` MEDIUMTEXT NULL,
  `DensidadePlantio_Cultura` FLOAT NULL COMMENT 'Densidade de plantio da cultura específica',
  `Espacamento_Sulcos` INT NULL COMMENT 'Espaçamento entre os sulcos em(cm)',
  `controle_daninhas` MEDIUMTEXT NULL COMMENT 'Capinas manuais, mecânicas ou químicas, dependendo da área',
  `Armazenamento` MEDIUMTEXT NULL COMMENT 'Armazenamento da cultura específica',
  `Temperatura` FLOAT NULL,
  `Armazenamento_Refrig` MEDIUMTEXT NULL,
  `IrrigacaoNecessaria` MEDIUMTEXT NULL,
  `luminosidade` MEDIUMTEXT NULL,
  `FertilidadeSolo` MEDIUMTEXT NULL,
  `Fertilizantes` MEDIUMTEXT NULL,
  `cultivaresecertificadas` MEDIUMTEXT NULL,
  PRIMARY KEY (`idCultura_Tratamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Dados_Sis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Dados_Sis` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Dados_Sis` (
  `idDados` INT(11) NOT NULL AUTO_INCREMENT,
  `Area_sistema` DECIMAL(10,5) NULL COMMENT 'em hectares',
  `Densidade_Plantio` DECIMAL(10,5) NULL,
  `CoberturaVegetalMedia` DECIMAL(10,5) NULL,
  `RendimentoMedioCulturas` DECIMAL(10,5) NULL COMMENT 'em toneladas por hectare',
  `TxRegeneracaoSistema` DECIMAL(10,5) NULL COMMENT 'Taxa de regeneração do sistema em %',
  `Sis_Var_idSis_Var` INT(11) NULL,
  PRIMARY KEY (`idDados`),
  INDEX `fk_Dados_Sis_Sis_Var1_idx` (`Sis_Var_idSis_Var` ASC) VISIBLE,
  CONSTRAINT `fk_Dados_Sis_Sis_Var1`
    FOREIGN KEY (`Sis_Var_idSis_Var`)
    REFERENCES `AgroFlorestaSIM`.`Sis_Var` (`idSis_Var`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Passoas_Culturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Passoas_Culturas` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Passoas_Culturas` (
  `Culturas_idCulturas` INT(11) NOT NULL,
  `Pessoa_idPessoa` INT(11) NOT NULL,
  PRIMARY KEY (`Culturas_idCulturas`, `Pessoa_idPessoa`),
  INDEX `fk_Culturas_has_Pessoa_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  INDEX `fk_Culturas_has_Pessoa_Culturas1_idx` (`Culturas_idCulturas` ASC) VISIBLE,
  CONSTRAINT `fk_Culturas_has_Pessoa_Culturas1`
    FOREIGN KEY (`Culturas_idCulturas`)
    REFERENCES `AgroFlorestaSIM`.`Culturas` (`idCulturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Culturas_has_Pessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `AgroFlorestaSIM`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Pessoa` (
  `idPessoa` INT(11) NOT NULL AUTO_INCREMENT,
  `email` MEDIUMTEXT NULL,
  `senha` MEDIUMTEXT NULL,
  `Sistema_idSistema` INT(11) NULL,
  `Coleta_idColeta` INT NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `fk_Pessoa_Sistema1_idx` (`Sistema_idSistema` ASC) VISIBLE,
  INDEX `fk_Pessoa_Coleta1_idx` (`Coleta_idColeta` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Sistema1`
    FOREIGN KEY (`Sistema_idSistema`)
    REFERENCES `AgroFlorestaSIM`.`Sistema` (`idSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_Coleta1`
    FOREIGN KEY (`Coleta_idColeta`)
    REFERENCES `AgroFlorestaSIM`.`Coleta` (`idColeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`PropositoCultivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`PropositoCultivo` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`PropositoCultivo` (
  `idPropositoCultivo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idPropositoCultivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`ReferenciaCulturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`ReferenciaCulturas` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`ReferenciaCulturas` (
  `idReferenciaCulturas` INT(11) NOT NULL AUTO_INCREMENT,
  `Referencias_idReferencias` INT(11) NULL,
  `Obersavacoes` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idReferenciaCulturas`),
  INDEX `fk_ReferenciaCulturas_Referencias1_idx` (`Referencias_idReferencias` ASC) VISIBLE,
  CONSTRAINT `fk_ReferenciaCulturas_Referencias1`
    FOREIGN KEY (`Referencias_idReferencias`)
    REFERENCES `AgroFlorestaSIM`.`Referencias` (`idReferencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Referencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Referencias` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Referencias` (
  `descricao_referencia` VARCHAR(1000) NULL COMMENT 'Observaçãoes, como por exemplo o link de um site ou o nome do livro.\\\\\\\\n',
  `idReferencias` INT(11) NOT NULL AUTO_INCREMENT,
  `Tipo_referencia` ENUM('1', '2', '3', '4', '99') NULL COMMENT 'especifique o tipo de referência:\\\\\\\\n1-Artigo Ciêntífico;\\\\\\\\n2-Livros;\\\\\\\\n3-Sites;\\\\\\\\n4-Trabalhos acadêmicos;\\\\\\\\n',
  PRIMARY KEY (`idReferencias`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Relac_Cultivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Relac_Cultivo` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Relac_Cultivo` (
  `idRelac_Cultivo` INT(11) NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL COMMENT '1-QUem ajudamos\\\\\\\\n2- Quem nos ajuda',
  `Culturas_idPrincipal` INT(11) NULL,
  `Culturas_idSecundaria` INT(11) NULL,
  PRIMARY KEY (`idRelac_Cultivo`),
  INDEX `fk_Relac_Cultivo_Culturas1_idx` (`Culturas_idPrincipal` ASC) VISIBLE,
  INDEX `fk_Relac_Cultivo_Culturas2_idx` (`Culturas_idSecundaria` ASC) VISIBLE,
  CONSTRAINT `fk_Relac_Cultivo_Culturas1`
    FOREIGN KEY (`Culturas_idPrincipal`)
    REFERENCES `AgroFlorestaSIM`.`Culturas` (`idCulturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relac_Cultivo_Culturas2`
    FOREIGN KEY (`Culturas_idSecundaria`)
    REFERENCES `AgroFlorestaSIM`.`Culturas` (`idCulturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Requisitos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Requisitos` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Requisitos` (
  `idRequisitos` INT(11) NOT NULL AUTO_INCREMENT,
  `Descricao` TINYTEXT NULL,
  `Tipo` ENUM('1', '2', '3', '4', '5') NULL COMMENT '1- climatica\\\\\\\\n2- luminosa ',
  `Adubacao` INT NULL COMMENT 'Tipo de adubação em kg/hec',
  `Requisitoscol` VARCHAR(45) NULL,
  `idReferenciaCulturas` INT(11) NULL,
  PRIMARY KEY (`idRequisitos`),
  INDEX `fk_Requisitos_ReferenciaCulturas1_idx` (`idReferenciaCulturas` ASC) VISIBLE,
  CONSTRAINT `fk_Requisitos_ReferenciaCulturas1`
    FOREIGN KEY (`idReferenciaCulturas`)
    REFERENCES `AgroFlorestaSIM`.`ReferenciaCulturas` (`idReferenciaCulturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Sistema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Sistema` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Sistema` (
  `idSistema` INT(11) NOT NULL AUTO_INCREMENT,
  `Dados_idDados` INT(11) NULL,
  PRIMARY KEY (`idSistema`),
  INDEX `fk_Sistema_Dados1_idx` (`Dados_idDados` ASC) VISIBLE,
  CONSTRAINT `fk_Sistema_Dados1`
    FOREIGN KEY (`Dados_idDados`)
    REFERENCES `AgroFlorestaSIM`.`Dados_Sis` (`idDados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`Sis_Var`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`Sis_Var` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`Sis_Var` (
  `idSis_Var` INT(11) NOT NULL AUTO_INCREMENT,
  `NumParcelas_Sis` DECIMAL(2,2) NULL,
  `NumPlantasParc_Sis` DECIMAL(2,2) NULL COMMENT 'numero de plantas por parcela',
  `Sis_EspacamentoPLantas` DECIMAL(2,2) NULL COMMENT 'Espaçamento entre as plantas(em metrosO)',
  `Sis_Tempo` INT(11) NULL COMMENT 'tempo em anos',
  `Culturas_idCulturas` INT(11) NULL,
  PRIMARY KEY (`idSis_Var`),
  INDEX `fk_Sis_Var_Culturas1_idx` (`Culturas_idCulturas` ASC) VISIBLE,
  CONSTRAINT `fk_Sis_Var_Culturas1`
    FOREIGN KEY (`Culturas_idCulturas`)
    REFERENCES `AgroFlorestaSIM`.`Culturas` (`idCulturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Variaveis do sistema';


-- -----------------------------------------------------
-- Table `AgroFlorestaSIM`.`TipoCultivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AgroFlorestaSIM`.`TipoCultivo` ;

CREATE TABLE IF NOT EXISTS `AgroFlorestaSIM`.`TipoCultivo` (
  `idTipoCultivo` INT NOT NULL AUTO_INCREMENT,
  `TIpo_Plantio` ENUM('1', '2', '3') NULL COMMENT 'Tipo de plantio:\n1-Manual\n2-Mecânico\n3-outro',
  `descricao` MEDIUMTEXT NULL,
  PRIMARY KEY (`idTipoCultivo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
